repos:

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
    - id: terraform-fmt
      name: terraform linting
    - id: terraform-validate
      name: terraform validation

- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_tfsec
      name: terraform security scan
      files: ^ops/

- repo: https://github.com/yelp/detect-secrets.git
  rev: v1.1.0
  hooks:
  -   id: detect-secrets
      name: detect secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: waf.tf

- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.17
  hooks:
  - id: circleci-config-validate
    name: circleci validation
  - id: shellcheck
    name: shell scripts linting

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
      name: trailing whitespace
    - id: end-of-file-fixer
      name: end of file fixer
    - id: check-added-large-files
      name: check added large files
