version: 2.1

parameters:
  terraform-image:
    type: string
    default: "hashicorp/terraform:0.14.8"

jobs:
  apply:
    docker:
      - image: << pipeline.parameters.terraform-image >>
    parameters:
      extension:
        type: string
    environment:
      GOOGLE_CLOUD_KEYFILE_JSON: /tmp/.gcloud.json
    steps:
      - checkout
      - run:
          name: add gcp key
          command: echo $GOOGLE_CREDENTIALS > $GOOGLE_CLOUD_KEYFILE_JSON
      - run:
          name: terraform init
          command: terraform init
                    -backend-config="bucket=${BACKEND_BUCKET}"
                    -backend-config="prefix=cloudflare/${BASENAME}.<< parameters.extension >>" ./ops
      - run:
          name: terraform validate
          command: terraform validate ./ops
      - run:
           name: terraform plan
           command: terraform plan -var-file="./ops/config/${BASENAME}.<< parameters.extension >>.tfvars" -out=plan ./ops
      - run:
           name: terraform apply
           command: terraform apply -auto-approve plan

workflows:
  commit:
    jobs:
      - apply:
          name: dev-domain
          extension: dev
      - apply:
          name: io-domain
          extension: io
          requires:
            - dev-domain
